DEFAULT_NAMESPACE = "default"

API_VERSION_V1 = "v1"

NAMESPACE_KIND = "Namespace"
POD_KIND = "Pod"
PERSISTENT_VOLUME_CLAIM_KIND = "PersistentVolumeClaim"
SECRET_KIND = "Secret"
SECRET_TYPE_DOCKER_CONFIG = "kubernetes.io/dockerconfigjson"
SECRET_DATA_DOCKER_CONFIG = {
    '.dockerconfigjson': 'eyJhdXRocyI6eyJzd3IuY24tbm9ydGgtNC5teWh1YXdlaWNsb3VkLmNvbSI6eyJ1c2VybmFtZSI6ImNuLW5vcnRoLTRAWlhYSlVGTENDNEJFMU5IR0FWSzQiLCJwYXNzd29yZCI6ImZjOWZmYTU3ZjI4YzdhNzZjMjgzNTE4Njk4NTBmZTg2MjU0MjNlYjBjZmY2NThhYzNiYTBjMGY0ZTUxZWIyYmYiLCJhdXRoIjoiWTI0dGJtOXlkR2d0TkVCYVdGaEtWVVpNUTBNMFFrVXhUa2hIUVZaTE5EcG1ZemxtWm1FMU4yWXlPR00zWVRjMll6STRNelV4T0RZNU9EVXdabVU0TmpJMU5ESXpaV0l3WTJabU5qVTRZV016WW1Fd1l6Qm1OR1UxTVdWaU1tSm0ifX19'}
SECRET_NAME_DOCKER_CONFIG = "huaweicloud-bj-registry"

IMAGE_PULL_POLICY_ALWAYS = "always"
IMAGE_PULL_POLICY_IF_NOT_PRESENT = "IfNotPresent"

RESTART_POLICY_NEVER = "Never"

# resource requirement fields
RESOURCE_REQUIREMENTS_CPU = "cpu"
RESOURCE_REQUIREMENTS_MEMORY = "memory"
RESOURCE_REQUIREMENTS_GPU = "nvidia.com/gpu"
RESOURCE_REQUIREMENTS_STORAGE = "storage"
RESOURCE_REQUIREMENTS_ATTRIBUTE_SETS = frozenset(
    [RESOURCE_REQUIREMENTS_CPU, RESOURCE_REQUIREMENTS_MEMORY, RESOURCE_REQUIREMENTS_GPU])

# storage mount fields
VOLUME_MOUNT_NAME = "name"
VOLUME_MOUNT_PATH = "mount_path"
VOLUME_MOUNT_ATTRIBUTE_SETS = frozenset([VOLUME_MOUNT_NAME, VOLUME_MOUNT_PATH])

VOLUME_ACCESS_MODE_READ_WRITE_MANY = "ReadWriteMany"
VOLUME_STORAGE_CLASS_JUICEFS = "juicefs-mvp"
