DEFAULT_NAMESPACE = "default"


API_VERSION_V1 = "v1"


NAMESPACE_KIND = "Namespace"
POD_KIND = "Pod"
PERSISTENT_VOLUME_CLAIM_KIND = "PersistentVolumeClaim"

IMAGE_PULL_POLICY_ALWAYS = "always"
IMAGE_PULL_POLICY_IF_NOT_PRESENT = "IfNotPresent"


# resource requirement fields
RESOURCE_REQUIREMENTS_CPU = "cpu"
RESOURCE_REQUIREMENTS_MEMORY = "memory"
RESOURCE_REQUIREMENTS_STORAGE = "storage"
RESOURCE_REQUIREMENTS_ATTRIBUTE_SETS = frozenset([RESOURCE_REQUIREMENTS_CPU, RESOURCE_REQUIREMENTS_MEMORY])

# storage mount fields
VOLUME_MOUNT_NAME = "name"
VOLUME_MOUNT_PATH = "mount_path"
VOLUME_MOUNT_ATTRIBUTE_SETS = frozenset([VOLUME_MOUNT_NAME, VOLUME_MOUNT_PATH])


VOLUME_ACCESS_MODE_READ_WRITE_MANY = "ReadWriteMany"
VOLUME_STORAGE_CLASS_JUICEFS = "juicefs-mvp"