---
apiVersion: v1
kind: Service
metadata:
  name: cluster
  namespace: juece
  labels:
    app: cluster
    service: cluster
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: cluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juece-cluster
  labels:
    account: cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-v1
  namespace: juece
  labels:
    app: cluster
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster
      version: v1
  template:
    metadata:
      labels:
        app: cluster
        version: v1
    spec:
      serviceAccountName: huanghe-admin
      containers:
      - name: cluster
        image: containers.git.digitalbrain.cn/engineering-group/huanghe.cluster:2022-11-24.12
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PYTHONPATH
          value: /source
        volumeMounts:
        - name: service-config
          mountPath: /etc/juece/config.yaml
          subPath: cluster
      volumes:
      - name: service-config
        configMap:
          name: service-config
          items:
          - key: cluster
            path: cluster
      imagePullSecrets:
      - name: db-container
---