---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  namespace: juece
  labels:
    app: notebook
    service: notebook
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: notebook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juece-notebook
  labels:
    account: notebook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-v1
  namespace: juece
  labels:
    app: notebook
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
      version: v1
  template:
    metadata:
      labels:
        app: notebook
        version: v1
    spec:
      serviceAccountName: juece-notebook
      containers:
      - name: notebook
        image: containers.git.digitalbrain.cn/engineering-group/huanghe.notebook:2022-12-23.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: service-config
          mountPath: /etc/juece/config.yaml
          subPath: notebook
        env:
          - name: ENV
            value: DEV
          - name: PYTHONPATH
            value: /source
      volumes:
      - name: service-config
        configMap:
          name: service-config
          items:
          - key: notebook
            path: notebook
      imagePullSecrets:
      - name: db-container
---