---
apiVersion: v1
kind: Service
metadata:
  name: job
  namespace: juece
  labels:
    app: job
    service: job
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: job
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juece-job
  labels:
    account: job
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-v1
  namespace: juece
  labels:
    app: job
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job
      version: v1
  template:
    metadata:
      labels:
        app: job
        version: v1
    spec:
      serviceAccountName: juece-job
      containers:
      - name: job
        image: containers.git.digitalbrain.cn/engineering-group/huanghe.job:2022-12-23.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: service-config
          mountPath: /etc/juece/config.yaml
          subPath: job
        env:
          - name: ENV
            value: DEV
          - name: PYTHONPATH
            value: /source
      volumes:
      - name: service-config
        configMap:
          name: service-config
          items:
          - key: job
            path: job
      imagePullSecrets:
      - name: db-container
---