---
apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: juece
  labels:
    app: storage
    service: storage
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juece-storage
  labels:
    account: storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-v1
  namespace: juece
  labels:
    app: storage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
      version: v1
  template:
    metadata:
      labels:
        app: storage
        version: v1
    spec:
      serviceAccountName: juece-storage
      containers:
      - name: storage
        image: containers.git.digitalbrain.cn/engineering-group/huanghe.storage:2022-12-07.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: service-config
          mountPath: /etc/juece/config.yaml
          subPath: storage
        env:
        - name: PYTHONPATH
          value: /source
      volumes:
      - name: service-config
        configMap:
          name: service-config
          items:
          - key: storage
            path: storage
      imagePullSecrets:
      - name: db-container
---