---
apiVersion: v1
kind: Service
metadata:
  name: deployment
  namespace: juece
  labels:
    app: deployment
    service: deployment
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juece-deployment
  labels:
    account: deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-v1
  namespace: juece
  labels:
    app: deployment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment
      version: v1
  template:
    metadata:
      labels:
        app: deployment
        version: v1
    spec:
      serviceAccountName: juece-deployment
      containers:
      - name: deployment
        image: containers.git.digitalbrain.cn/engineering-group/huanghe.deployment:2022-12-23.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: service-config
          mountPath: /etc/juece/config.yaml
          subPath: deployment
        env:
          - name: ENV
            value: DEV
          - name: PYTHONPATH
            value: /source
      volumes:
      - name: service-config
        configMap:
          name: service-config
          items:
          - key: deployment
            path: deployment
      imagePullSecrets:
      - name: db-container
---