#python3.8
#ARG BASE_IMG=containers.git.digitalbrain.cn/engineering-group/huanghe.backend-base:2023-01-04.3
#python3.11
ARG BASE_IMG=containers.git.digitalbrain.cn/engineering-group/huanghe.backend-base:2023-02-24.13
FROM $BASE_IMG
WORKDIR /source/services/job_management

# python dependence
COPY ./job/requirements.txt .
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
