from typing import Optional, List


class V1NamespaceStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'conditions': 'list[V1NamespaceCondition]',
        'phase': 'str'
    }
    conditions: List
    """
    Represents the latest available observations of a namespace's current state.  # noqa: E501
    """
    phase: Optional[str]
    """
    Phase is the current lifecycle phase of the namespace. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/    # noqa: E501
    """
    attribute_map = {
        'conditions': 'conditions',
        'phase': 'phase'
    }
