# syntax=docker/dockerfile:1.4
ARG BASE_IMG=containers.git.digitalbrain.cn/engineering-group/huanghe.backend-base:2023-01-04.3
FROM $BASE_IMG
WORKDIR /source/services/storage

# python dependence
COPY services/storage/requirements.txt .
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
