# coding: utf-8
from __future__ import annotations
from services.cluster.k8s.model.base_model import BaseModel
from services.cluster.k8s.model.v1_alpha1_volcano_job_spec import V1Alpha1VolcanoJobSpec
from services.cluster.k8s.model.v1_object_meta import V1ObjectMeta
from services.cluster.k8s.const.crd_kubeflow_const import VOLCANO_V1_ALPHA1_API_VERSION, VOLCANO_JOB_KIND


class V1Alpha1VolcanoJob(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    spec: V1Alpha1VolcanoJobSpec
    openapi_types = {
        'api_version': 'str',
        'kind': 'str',
        'metadata': 'V1ObjectMeta',
        'spec': 'V1Alpha1VolcanoJobSpec',
        # 'status': 'V1NotebookStatus'
    }

    attribute_map = {
        'api_version': 'apiVersion',
        'kind': 'kind',
        'metadata': 'metadata',
        'spec': 'spec',
        'status': 'status'
    }

    @classmethod
    def default(cls, name, namespace, image, labels, resource, envs, volumes, tolerations, command, working_dir,
                annotations, task_num, mode):
        return cls.new(api_version=VOLCANO_V1_ALPHA1_API_VERSION,
                       kind=VOLCANO_JOB_KIND,
                       metadata=V1ObjectMeta.without_istio_injection(name=name, namespace=namespace, labels=labels,
                                                                     annotations=annotations),
                       spec=V1Alpha1VolcanoJobSpec.default(name=name, image=image, resource=resource, envs=envs,
                                                           volumes=volumes, tolerations=tolerations, command=command,
                                                           working_dir=working_dir, task_num=task_num, mode=mode),
                       status=None)

    @staticmethod
    def new(api_version: str, kind: str, metadata: V1ObjectMeta, spec: V1Alpha1VolcanoJobSpec, status):
        return V1Alpha1VolcanoJob(api_version=api_version, kind=kind, metadata=metadata, spec=spec, status=status)
