from __future__ import annotations
from k8s.model.generic_mixin import GenericMixin
from k8s.model.v1_pod_spec import V1PodSpec


class V1Alpha1VolcanoJobTaskTemplate(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    spec: V1PodSpec
    openapi_types = {
        'spec': 'V1PodSpec',
    }

    attribute_map = {
        'spec': 'spec',
    }

    @classmethod
    def default(cls, name, image, resource, envs, volumes, tolerations):
        return cls.new(spec=V1PodSpec.notebook(name=name, image=image, resource=resource, envs=envs, volumes=volumes, tolerations=tolerations))

    @staticmethod
    def new(spec: V1PodSpec) -> V1Alpha1VolcanoJobTaskTemplate:
        return V1Alpha1VolcanoJobTaskTemplate(spec=spec)



if __name__ == '__main__':
    s = V1PodSpec()
    s.to_dict()