from services.cluster.k8s.model.base_model import GenericMixin


class V1Beta1IngressBackend(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    service_name: str
    service_port: str

    openapi_types = {
        "service_name": "str",
        "service_port": "str",
    }

    attribute_map = {
        'service_name': "serviceName",
        "service_port": "servicePort",
    }


    @classmethod
    def default(cls, service_name, service_port="80"):
        return cls.new(service_name=service_name, service_port=service_port)

    @staticmethod
    def new(service_name: str, service_port: str):
        return V1Beta1IngressBackend(service_name=service_name, service_port=service_port)