from services.cluster.k8s.model.base_model import GenericMixin
from services.cluster.k8s.model.v1_beta1_http_ingress_path import V1Beta1HTTPIngressPath
from typing import List

class V1Beta1HTTPIngressRuleValue(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    paths: List[V1Beta1HTTPIngressPath]
    openapi_types = {
        "paths": "List[V1Beta1HTTPIngressPath]",
    }

    attribute_map = {
        'paths': 'paths',
    }

    @classmethod
    def default(cls, service_name: str):
        return cls.new([V1Beta1HTTPIngressPath.default(service_name=service_name)])

    @staticmethod
    def new(paths: List[V1Beta1HTTPIngressPath]):
        return V1Beta1HTTPIngressRuleValue(paths=paths)