from services.cluster.k8s.model.base_model import GenericMixin
from services.cluster.k8s.const.crd_kubeflow_const import HUAWEICLOUD_NETWORK_CIDR, HUAWEICLOUD_NETWORK_AVAILABLE_ZONE, \
    HUAWEICLOUD_NETWORK_VPC_ID, HUAWEICLOUD_NETWORK_SUBNET_ID, HUAWEICLOUD_NETWORK_NETWORK_ID, HUAWEICLOUD_NETWORK_NETTYPE


class V1Beta1NetworkSpec(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """

    attached_vpc: str
    available_zone: str
    cidr: str
    network_id: str
    network_type: str
    subnet_id: str
    openapi_types = {
        'attached_vpc': 'str',
        'available_zone': 'str',
        'cidr': 'str',
        'network_id': 'str',
        'network_type': 'str',
        'subnet_id': 'str',
    }

    attribute_map = {
        'attached_vpc': 'attachedVPC',
        'available_zone': 'availableZone',
        'cidr': "cidr",
        "network_id": "networkID",
        "network_type": "networkType",
        "subnet_id": "subnetID",
    }


    @classmethod
    def default(cls):
        return cls.new(attached_vpc=HUAWEICLOUD_NETWORK_VPC_ID,
                       available_zone=HUAWEICLOUD_NETWORK_AVAILABLE_ZONE,
                       cidr=HUAWEICLOUD_NETWORK_CIDR,
                       network_id=HUAWEICLOUD_NETWORK_NETWORK_ID,
                       network_type=HUAWEICLOUD_NETWORK_NETTYPE,
                       subnet_id=HUAWEICLOUD_NETWORK_SUBNET_ID
                       )

    @staticmethod
    def new(attached_vpc: str, available_zone: str, cidr: str, network_id: str, network_type: str, subnet_id: str):
        return V1Beta1NetworkSpec(attached_vpc=attached_vpc,
                                  available_zone=available_zone,
                                  cidr=cidr,
                                  network_id=network_id,
                                  network_type=network_type,
                                  subnet_id=subnet_id,)
