from services.cluster.k8s.model.base_model import GenericMixin
from services.cluster.k8s.model.v1_beta1_http_ingress_rule_value import V1Beta1HTTPIngressRuleValue
from typing import Optional

class V1Beta1IngressRule(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    host: Optional[str]
    http: Optional[V1Beta1HTTPIngressRuleValue]
    openapi_types = {
        "host": "str",
        "http": "V1Beta1HTTPIngressRuleValue",
    }

    attribute_map = {
        'host': 'host',
        "http": "http",
    }


    @classmethod
    def default(cls, service_name: str):
        return cls.new(http=V1Beta1HTTPIngressRuleValue.default(service_name=service_name))

    @staticmethod
    def new(http: V1Beta1HTTPIngressRuleValue, host: Optional[str] = None):
        return V1Beta1IngressRule(host=host, http=http)