from services.cluster.k8s.model.generic_mixin import GenericMixin
from typing import List, Dict, Optional

class V1LabelSelector(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    match_expressions: Optional[List]
    match_labels: Dict[str, str]

    openapi_types = {
        'match_expressions': 'list[V1LabelSelectorRequirement]',
        'match_labels': 'dict(str, str)'
    }

    attribute_map = {
        'match_expressions': 'matchExpressions',
        'match_labels': 'matchLabels'
    }

    @classmethod
    def default(cls, match_labels: Dict[str, str]):
        return cls.new(match_labels=match_labels, match_expressions=None)

    @staticmethod
    def new(match_expressions: Optional[List], match_labels: Dict[str, str]):
        return V1LabelSelector(match_expressions=match_expressions, match_labels=match_labels)