from __future__ import annotations
from k8s.model.generic_mixin import GenericMixin


class V1LocalObjectReference(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    name: str
    value: str
    openapi_types = {
        'name': 'str',
    }

    attribute_map = {
        'name': 'name',
    }

    @staticmethod
    def new(name: str):
        return V1LocalObjectReference(name=name)