from __future__ import annotations
from services.cluster.k8s.model.generic_mixin import GenericMixin
from services.cluster.k8s.model.v1_notebook_template import V1NotebookTemplate


class V1NotebookSpec(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    template: V1NotebookTemplate
    openapi_types = {
        'template': 'V1NotebookTemplate',
    }
    attribute_map = {
        'template': 'template',
    }

    @classmethod
    def default(cls, name, image, resource, envs, volumes, tolerations):
        return cls.new(V1NotebookTemplate.default(name=name, image=image, resource=resource, envs=envs, volumes=volumes,
                                                  tolerations=tolerations))

    @staticmethod
    def new(template):
        return V1NotebookSpec(template=template)
