from __future__ import annotations
from k8s.model.generic_mixin import GenericMixin
from k8s.model.v1_notebook_template import V1NotebookTemplate

class V1NotebookSpec(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    template: V1NotebookTemplate
    openapi_types = {
        'template': 'V1NotebookTemplate',
    }
    attribute_map = {
        'template': 'template',
    }

    @classmethod
    def default(cls, name, image):
        return cls.new(V1NotebookTemplate.default(name=name, image=image))


    @staticmethod
    def new(template):
        return V1NotebookSpec(template=template)



if __name__ == '__main__':
    s = V1PodSpec()
    s.to_dict()