from services.cluster.k8s.model.generic_mixin import GenericMixin
from typing import Optional, List


class V1NamespaceSpec(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    finalizers: Optional[List[str]]
    openapi_types = {
        'finalizers': 'list[str]'
    }

    attribute_map = {
        'finalizers': 'finalizers'
    }

    @staticmethod
    def new(finalizers: Optional[List[str]]):
        return V1NamespaceSpec(finalizers=finalizers)
