from __future__ import annotations
from typing import Optional
from k8s.model.generic_mixin import GenericMixin


class V1PersistentVolumeClaimVolumeSource(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    claim_name: str
    read_only: Optional[bool]
    openapi_types = {
        'claim_name': 'str',
        'read_only': 'bool'
    }

    attribute_map = {
        'claim_name': 'claimName',
        'read_only': 'readOnly'
    }

    @classmethod
    def default(cls, claim_name: str):
        return cls.new(claim_name=claim_name, read_only=False)

    @staticmethod
    def new(claim_name: str, read_only: bool):
        return V1PersistentVolumeClaimVolumeSource(claim_name=claim_name, read_only=read_only)
