from k8s.model.generic_mixin import GenericMixin
from typing import Optional

class V1VolumeMount(GenericMixin):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    mount_path: str
    name: str
    read_only: Optional[bool]
    sub_path: Optional[str]
    sub_path_expr: Optional[str]
    mount_propagation: Optional[str]

    openapi_types = {
        'mount_path': 'str',
        'mount_propagation': 'str',
        'name': 'str',
        'read_only': 'bool',
        'sub_path': 'str',
        'sub_path_expr': 'str'
    }

    attribute_map = {
        'mount_path': 'mountPath',
        'mount_propagation': 'mountPropagation',
        'name': 'name',
        'read_only': 'readOnly',
        'sub_path': 'subPath',
        'sub_path_expr': 'subPathExpr'
    }


    @classmethod
    def default(cls, name: str, mount_path: str, mount_propagation: Optional[str] = None):
        return cls.new(name=name, mount_path=mount_path, mount_propagation=mount_propagation,
                       sub_path=None, sub_path_expr=None, read_only=None)

    @staticmethod
    def new(name: str, mount_path: str, mount_propagation: Optional[str],
            sub_path: Optional[str], sub_path_expr: Optional[str], read_only: Optional[bool]):
        return V1VolumeMount(name=name, mount_path=mount_path, mount_propagation=mount_propagation,
                             sub_path=sub_path, sub_path_expr=sub_path_expr, read_only=read_only)

