# syntax=docker/dockerfile:1.4
ARG BASE_IMG=containers.git.digitalbrain.cn/engineering-group/huanghe.backend-base:2023-02-24.11
FROM $BASE_IMG
WORKDIR /source/services/user


# python dependence
COPY ./user/requirements.txt .
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
